# Generated by Django 3.1 on 2020-12-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='static/images/room/')),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
