# Generated by Django 3.1 on 2020-12-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.CharField(default='', max_length=20),
        ),
    ]
